language: node_js
node_js:
  - 7
cache:
  directories:
    - node_modules
git:
  submodules: false
before_install:
  - chmod +x update_sub.sh
  - echo -e "\n\nmachine github.com\n  login $CI_USER_TOKEN\n" >~/.netrc
  - git submodule update --init --recursive
install:
  - npm i
before_script:
  - git submodule foreach git pull origin master
script:
  - npm run build
after_success:
  - ./update_sub.sh
